mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
logging:
  config: classpath:logback-spring.xml
  path: D:/demolog/log
server:
  port: 9998
spring:
  datasource:
    url: jdbc:mysql://47.98.146.179:3306/shuang?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: ws960802
  redis:
    host: 127.0.0.1
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB